In [130]:
import pandas as pd

# 5.1 Introduction to pandas Data Structures

In [131]:
from pandas import Series, DataFrame

### Series

In [132]:
obj = pd.Series([4, 7, -5, 3])

In [133]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

And so on...

In [134]:
obj.values

array([ 4,  7, -5,  3])

In [135]:
obj.index


RangeIndex(start=0, stop=4, step=1)

In [136]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [137]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [138]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b",  "a", "c"])

In [139]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [140]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [141]:
obj2["a"]

-5

In [142]:
obj2["d"] = 6

In [143]:
obj2["d"]

6

In [144]:
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [145]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [146]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [147]:
import numpy as np


In [148]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [149]:
"b" in obj2

True

In [150]:
"e" in obj2

False

In [151]:
sdata = {"Ohio": 3500, "Texas": 71000, "Oregon":16000, "Utah": 5000}

In [152]:
obj3= pd.Series(sdata)

In [153]:
obj3

Ohio       3500
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [154]:
obj3.to_dict()

{'Ohio': 3500, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [155]:
states = ["California", "Ohio", "Oregon", "Texas"]

In [156]:
obj4 = pd.Series(sdata, index=states)

In [157]:
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [158]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [159]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [160]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [161]:
obj3

Ohio       3500
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [162]:
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [163]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [164]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]

In [165]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [166]:
data = {"state":["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [167]:
frame = pd.DataFrame(data)

In [168]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [169]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [170]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [171]:
frame2 = pd.DataFrame(data, columns = ["year", "state", "pop", "debt"])

In [172]:
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [173]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [174]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [175]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [176]:
frame2.loc[0]

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: 0, dtype: object

In [177]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [178]:
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

frame2["debt"] = 66.7

In [179]:
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [180]:
val = pd.Series([-1.2, -1.5, -1.7], index=[2, 4, 5])

In [181]:
frame2["debt"] = val

In [182]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7

In [183]:
frame2["eastern"] = frame2["state"]=="Ohio"

In [184]:
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6  -1.2     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9  -1.5    False
5  2003  Nevada  3.2  -1.7    False

In [185]:
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6  -1.2     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9  -1.5    False
5  2003  Nevada  3.2  -1.7    False

In [186]:
del frame2["eastern"]

In [187]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7

In [188]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [189]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
   ....:                "Nevada": {2001: 2.4, 2002: 2.9}}

In [190]:
frame3 = pd.DataFrame(populations)

In [191]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [192]:
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [193]:
In [77]: pdata = {"Ohio": frame3["Ohio"][:-1],
   ....:          "Nevada": frame3["Nevada"][:2]}

In [78]: pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [194]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [195]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [196]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, -1.2],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -1.5],
       [2003, 'Nevada', 3.2, -1.7]], dtype=object)

In [197]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])

In [198]:
index = obj.index

In [199]:
index

Index(['a', 'b', 'c'], dtype='object')

In [200]:
index[1:]

Index(['b', 'c'], dtype='object')

In [201]:
index[1] = "d"

TypeError: Index does not support mutable operations

In [202]:
labels = pd.Index(np.arange(3))

In [203]:
labels

Index([0, 1, 2], dtype='int64')

In [204]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)


In [205]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [206]:
obj2.index is labels

True

In [207]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [208]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object')

In [209]:
"Ohio" in frame3.columns

True

In [210]:
2003 in frame3.index

False

In [211]:
pd.Index(["foo", "foo", "bar", "bar"])


Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [212]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ["d", "b", "a", "c"])

In [213]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [214]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])

In [215]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [216]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

In [217]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [218]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
   .....:                      index=["a", "c", "d"],
   .....:                      columns=["Ohio", "Texas", "California"])


In [219]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [220]:
frame2 = frame.reindex(index = ["a", "b", "c", "d"])

In [221]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [222]:
states = ["Texas", "Utah", "California"]

In [223]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [224]:
frame.reindex(states, axis="columns")

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [225]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

California  Texas
a           2      1
d           8      7
c           5      4

In [227]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])

In [228]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [229]:
new_obj = obj.drop("c")

In [230]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [231]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [234]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), 
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns = ["one", "two", "three", "four"])

In [235]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [237]:
data.drop(index=["Colorado", "Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [239]:
data.drop(columns=["two"])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [240]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [242]:
data.drop("two", axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [245]:
data.drop(["two", "four"], axis = "columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14